### ISSUE TITLE
Rename to low-resource-languages

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/low-resource-languages#111]
I feel that endangered-languages gives the wrong impression of this repo and it's goals to our audience. This repo should be for low-resource languages, all of them, and not just ones which are considered endangered. 

Should we change it?

**Comment by alketii** [comment]
Yes I think low-resource is much better which somehow also makes sense for endangered.

**Comment by RichardLitt** [comment]
@HughP? @cesine?

**Comment by HughP** [comment]
The issue was audience. Very few if any people in the endangered language community (researchers and speakers) follow the term "low-resource languages". It is many of these people who are looking for software and are getting grants to create new software. So, I feel for us to be maximally successful we need to put our work under their noses in a manner they will find it. That said I acknowledge that we are also dealing with low-resource languages. However, our audience does not often recognize that term.

**Comment by RichardLitt** [comment]
That's a pretty fair point. 

Maybe just a larger disclaimer. Will think about it.

**Comment by roedoejet** [comment]
Yes, important not to over-represent endangerment and under-represent all of the hard work that is happening. But maximizing the audience is a good consideration. Maybe just making a note explaining the understanding that endangered languages isn't the best term?

**Comment by RichardLitt** [comment]
I've spent a good deal of time looking at the literature on this recently (as part of my much delayed [thesis work](https://github.com/RichardLitt/thesis)), and I don't feel comfortable with `endangered-languages`. Terminologically, 'low-resource' is intentionally somewhat neutral, as compared to 'minority', 'endangered', or other terms that reflect Western viewpoints. Similarly, using the term _language vitality_ as opposed to _language endangerment_ "represents a significant shift in the representation of attitudes toward the rhetoric of indigenous languages to one away from dire predictions about endangerment to action-oriented attitudes about vitality and sustainability." (Grenoble 2016, from "A response to 'Assessing levels of endangerment in the Catalogue of Endangered Languages (ELCat) using the Language Endangerment Index (LEI)") 

Given this, I am going to change the name to low-resource-languages. It should redirect fine, so there's nothing for anyone to update.
